### ISSUE TITLE
Note module - Rajesh's Team

### ISSUE THREAD

**Issue by hadiyarajesh** [NoteXCommunity/note-x#5]
**Description**
We need to work on below tasks to complete the note taking feature in app

**Tasks**
- [ ] Create note taking app UI
- [ ] Allow CRUD operation on notes
- [ ] Allow user to create folders and move note to specified folder
