### ISSUE TITLE
Note module - Siddu's Team

### ISSUE THREAD

**Issue by hadiyarajesh** [NoteXCommunity/note-x#6]
**Description**
We need to work on below tasks to complete the reminder taking feature in app

**Tasks**
- [ ] Create reminder taking app UI
- [ ] Allow CRUD operation on reminder
- [ ] Allow user to quickly select time by using chips like today, tomorrow etc
