### ISSUE TITLE
Settings module - Loveleen's Team

### ISSUE THREAD

**Issue by hadiyarajesh** [NoteXCommunity/note-x#7]
**Description**
We need to work on below tasks to complete the settings feature in app

**Tasks**
- [ ] Create Settings UI
- [ ] Allow users to choose different settings like app language, default sort type, etc
- [ ] Allow user to set options like playing sound for reminders

**Comment by hadiyarajesh** [comment]
Assigned to @hadiyarajesh team as Loveleen left the team.
