### ISSUE TITLE
Background work/Notification module - Geet's Team

### ISSUE THREAD

**Issue by hadiyarajesh** [NoteXCommunity/note-x#8]
**Description**
We need to work on below tasks to complete the note taking app

**Tasks**
- [ ] Work on background work for reminders
- [ ] Work on notification
- [ ] Create deleted notes UI
